### PR TITLE
Keyword and Extension arg parsing

### PR DESCRIPTION
**Pull request by ttufts**
Changed arg parsing for keywords and extensions to use nargs instead of manually splitting.

argparse is awesome :-)

### CODE REVIEW

**Comment by bgx4k3p** [comment]
Thanks! I was looking trough the documentation for nargs, but didn't try it. This is definitely more efficient.

**Comment by ttufts** [comment]
I realized I didn't remove the original lines, just commented them. Didn't
feel like making a whole new pull request for it though. You can more
easily yank those and commit the changes.

**Comment by ttufts** [comment]
Did that change break something? I see you reversed it...

**Comment by bgx4k3p** [comment]
I revered the first one because of the ‘.’ in the extensions and need to update the documentation. I’ll look at the changes you submitted tonight as I’m at work right now can’t spend too much time. Definitely appreciate the help!

**Comment by ttufts** [comment]
No problem. I fixed the '.' in the next update, then added the suggestion
that someone on NOVAHA suggested for searching files as they are found
rather than building the search list first. Definitely speeds it up a
little. Finally, you didn't use the 'default' parameter in argparse at all
and it cleans up the code a bit, so I implemented that.

Glad to help!

**Pull request merged**
